In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [2]:
tennis = pd.read_csv('dati/tennis.csv')
male = pd.read_csv('dati/male_players.csv')
female = pd.read_csv('dati/female_players.csv')

C:\Users\Francesco\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
test = pd.read_csv('output/match.csv')
test1 = pd.read_csv('output/tournament.csv')

In [6]:
test1

,tourney_pk,tourney_id,date_id,tourney_name,surface,draw_size,tourney_level,tourney_spectators,tourney_revenue
0,2017-W-WITF-FIN-02A-201715201730731Savitaipale...,2017-W-WITF-FIN-02A-2017,201730731,Savitaipale $15K,Clay,32,15,2338,490042.49
1,2021-0403M202110322Miami Masters,2021-0403,202110322,Miami Masters,Hard,128,M,11178,2495193.80
2,2021-7791C202120607Almaty CH,2021-7791,202120607,Almaty CH,Clay,32,C,3734,702890.14
3,2016-W-C10-AUT-03A-201610201630815Graz $10K,2016-W-C10-AUT-03A-2016,201630815,Graz $10K,Clay,32,10,3315,748155.54
4,2017-W-FC-2017-G2-AO-B-M-HKG-IRI-01D201730720F...,2017-W-FC-2017-G2-AO-B-M-HKG-IRI-01,201730720,Fed Cup G2 RR: HKG vs IRI,Hard,2,D,223,43951.16
...,...,...,...,...,...,...,...,...,...
4907,2017-W-WITF-THA-03A-201725201720508Hua Hin $25K,2017-W-WITF-THA-03A-2017,201720508,Hua Hin $25K,Hard,32,25,3464,645465.26
4908,2016-W-FC-2016-G1-EPA-A-M-SWE-UKR-01D201610205...,2016-W-FC-2016-G1-EPA-A-M-SWE-UKR-01,201610205,Fed Cup G1 RR: SWE vs UKR,Hard,2,D,162,31260.78
4909,2020-W-ITF-FRA-06A-202015202010309W15+H Amiens,2020-W-ITF-FRA-06A-2020,202010309,W15+H Amiens,Clay,32,15,2646,518701.19
4910,2016-W-C10-KAZ-04B-201610201630919Shymkent $10K,2016-W-C10-KAZ-04B-2016,201630919,Shymkent $10K,Clay,32,10,3550,664716.57
4911,2017-M035I201730731Washington,2017-M035,201730731,Washington,Hard,32,I,6701,1397851.41

In [13]:
test1[['tourney_id','date_id','surface']].drop_duplicates()
test1[['tourney_pk']].drop_duplicates()

                                             tourney_pk
0     2017-W-WITF-FIN-02A-201715201730731Savitaipale...
1                      2021-0403M202110322Miami Masters
2                          2021-7791C202120607Almaty CH
3           2016-W-C10-AUT-03A-201610201630815Graz $10K
4     2017-W-FC-2017-G2-AO-B-M-HKG-IRI-01D201730720F...
...                                                 ...
4907    2017-W-WITF-THA-03A-201725201720508Hua Hin $25K
4908  2016-W-FC-2016-G1-EPA-A-M-SWE-UKR-01D201610205...
4909     2020-W-ITF-FRA-06A-202015202010309W15+H Amiens
4910    2016-W-C10-KAZ-04B-201610201630919Shymkent $10K
4911                      2017-M035I201730731Washington

[4912 rows x 1 columns]

In [31]:
tennis

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
0,2019-M020,Brisbane,Hard,32,A,20181231,300,105453,NaN,Kei Nishikori,R,178.0,JPN,29.004791,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,6-4 3-6 6-2,3,F,124.0,3.0,3.0,77.0,44.0,31.0,17.0,13.0,3.0,6.0,8.0,6.0,100.0,54.0,34.0,20.0,14.0,10.0,15.0,9.0,3590.0,16.0,1977.0,3928,742618.69
1,2019-M020,Brisbane,Hard,32,A,20181231,299,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,104542,PR,Jo-Wilfried Tsonga,R,188.0,FRA,33.705681,7-6(6) 6-2,3,SF,82.0,10.0,1.0,52.0,33.0,28.0,14.0,10.0,0.0,1.0,17.0,2.0,77.0,52.0,36.0,7.0,10.0,10.0,13.0,16.0,1977.0,239.0,200.0,3928,742618.69
2,2019-M020,Brisbane,Hard,32,A,20181231,298,105453,NaN,Kei Nishikori,R,178.0,JPN,29.004791,104871,NaN,Jeremy Chardy,R,188.0,FRA,31.882272,6-2 6-2,3,SF,66.0,2.0,2.0,47.0,33.0,26.0,9.0,8.0,2.0,2.0,10.0,3.0,46.0,27.0,15.0,6.0,8.0,1.0,5.0,9.0,3590.0,40.0,1050.0,3928,742618.69
3,2019-M020,Brisbane,Hard,32,A,20181231,297,104542,PR,Jo-Wilfried Tsonga,R,188.0,FRA,33.705681,200282,NaN,Alex De Minaur,R,183.0,AUS,19.868583,6-4 7-6(2),3,QF,106.0,12.0,2.0,68.0,43.0,34.0,15.0,11.0,4.0,5.0,1.0,2.0,81.0,60.0,38.0,9.0,11.0,4.0,6.0,239.0,200.0,31.0,1298.0,3928,742618.69
4,2019-M020,Brisbane,Hard,32,A,20181231,296,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,105683,NaN,Milos Raonic,R,196.0,CAN,28.010951,6-7(2) 6-3 6-4,3,QF,129.0,12.0,3.0,105.0,68.0,48.0,25.0,16.0,8.0,8.0,29.0,5.0,94.0,56.0,46.0,19.0,15.0,2.0,4.0,16.0,1977.0,18.0,1855.0,3928,742618.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186068,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,204,215794,WC,Hurricane Tyra Black,R,NaN,USA,19.690623,222081,NaN,Eleana Yu,R,NaN,USA,16.002738,7-6(1) 6-1,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,598.0,57.0,1216.0,6.0,2312,471620.95
186069,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,205,210754,NaN,Vivian Heisen,U,NaN,GER,26.869268,220723,NaN,Jessica Livianu,R,NaN,USA,22.713210,2-6 6-2 10-3,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,429.0,102.0,729.0,35.0,2312,471620.95
186070,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,206,211874,NaN,Victoria Rodriguez,U,NaN,MEX,25.552361,202478,NaN,Tara Moore,R,NaN,GBR,28.260096,6-2 7-6(8),3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,643.0,48.0,454.0,93.0,2312,471620.95
186071,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,207,213789,NaN,Katarina Jokic,U,NaN,BIH,22.559890,205922,NaN,Chanelle Van Nguyen,U,NaN,USA,26.806297,6-4 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,923.0,17.0,627.0,51.0,2312,471620.95
186072,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,208,215306,NaN,Emiliana Arango,R,NaN,COL,19.947981,223453,WC,Brooklyn Olson,U,NaN,USA,NaN,6-1 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,493.0,83.0,NaN,NaN,2312,471620.95

In [3]:
tennis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186073 entries, 0 to 186072
Data columns (total 49 columns):
tourney_id            186073 non-null object
tourney_name          186073 non-null object
surface               185911 non-null object
draw_size             186073 non-null int64
tourney_level         186073 non-null object
tourney_date          186073 non-null int64
match_num             186073 non-null int64
winner_id             186073 non-null int64
winner_entry          25822 non-null object
winner_name           186073 non-null object
winner_hand           186057 non-null object
winner_ht             49328 non-null float64
winner_ioc            186073 non-null object
winner_age            183245 non-null float64
loser_id              186073 non-null int64
loser_entry           44146 non-null object
loser_name            186073 non-null object
loser_hand            186002 non-null object
loser_ht              38344 non-null float64
loser_ioc             186073 non-null object
loser_age             179571 non-null float64
score                 185898 non-null object
best_of               186073 non-null int64
round                 186073 non-null object
minutes               81636 non-null float64
w_ace                 82284 non-null float64
w_df                  82284 non-null float64
w_svpt                82284 non-null float64
w_1stIn               82284 non-null float64
w_1stWon              82284 non-null float64
w_2ndWon              82284 non-null float64
w_SvGms               82288 non-null float64
w_bpSaved             82284 non-null float64
w_bpFaced             82284 non-null float64
l_ace                 82284 non-null float64
l_df                  82284 non-null float64
l_svpt                82284 non-null float64
l_1stIn               82284 non-null float64
l_1stWon              82284 non-null float64
l_2ndWon              82284 non-null float64
l_SvGms               82288 non-null float64
l_bpSaved             82284 non-null float64
l_bpFaced             82284 non-null float64
winner_rank           166694 non-null float64
winner_rank_points    166678 non-null float64
loser_rank            150817 non-null float64
loser_rank_points     150801 non-null float64
tourney_spectators    186073 non-null int64
tourney_revenue       186073 non-null float64
dtypes: float64(28), int64(7), object(14)
memory usage: 69.6+ MB

In [30]:
id1 = np.unique(tennis.loser_id)
id2 = np.unique(tennis.winner_id)
len(id1) + len(id2)

16207

In [29]:
tennis[(tennis.loser_age.isna()) | (tennis.winner_age.isna())]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
5883,2019-M-DC-2019-G2-AM-M-MEX-PAR-01,Davis Cup G2 R1: MEX vs PAR,Clay,4,D,20190914,5,105688,NaN,Manuel Sanchez,R,NaN,MEX,28.676249,209226,NaN,Adolfo Daniel Vallejo,R,NaN,PAR,NaN,6-3 6-2,3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,830.0,16.0,NaN,NaN,486,100842.51
5890,2019-M-DC-2019-G2-AO-M-NZL-INA-01,Davis Cup G2 R1: NZL vs INA,Hard,4,D,20190914,4,209188,NaN,Ari Fahresi,U,NaN,INA,NaN,208055,NaN,Ajeet Rai,R,NaN,NZL,20.640657,6-3 2-6 [10-7],3,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,744.0,22.0,422,76121.74
6808,2018-M-DC-2018-G2-AM-M-PUR-MEX-01,Davis Cup G2 R1: PUR vs MEX,Hard,4,D,20180203,1,105688,NaN,Manuel Sanchez,R,NaN,MEX,27.066393,200620,NaN,Ignacio Garcia,NaN,NaN,PUR,NaN,7-6(5) 6-4,3,RR,106.0,7.0,5.0,72.0,51.0,33.0,8.0,11.0,4.0,7.0,0.0,5.0,79.0,59.0,35.0,8.0,11.0,3.0,7.0,560.0,54.0,NaN,NaN,479,90802.28
6810,2018-M-DC-2018-G2-AM-M-PUR-MEX-01,Davis Cup G2 R1: PUR vs MEX,Hard,4,D,20180203,4,105688,NaN,Manuel Sanchez,R,NaN,MEX,27.066393,200619,NaN,Sebastian Arcila,NaN,NaN,PUR,NaN,7-5 6-0,3,RR,73.0,3.0,1.0,50.0,32.0,25.0,11.0,9.0,4.0,5.0,0.0,1.0,59.0,42.0,22.0,6.0,9.0,2.0,7.0,560.0,54.0,NaN,NaN,479,90802.28
6811,2018-M-DC-2018-G2-AM-M-PUR-MEX-01,Davis Cup G2 R1: PUR vs MEX,Hard,4,D,20180203,5,106250,NaN,Luis Patino,R,NaN,MEX,24.314853,200620,NaN,Ignacio Garcia,NaN,NaN,PUR,NaN,7-5 6-2,3,RR,74.0,5.0,2.0,54.0,27.0,20.0,17.0,10.0,1.0,3.0,0.0,2.0,64.0,50.0,24.0,9.0,10.0,4.0,9.0,951.0,12.0,NaN,NaN,479,90802.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185940,2020-W-ITF-USA-42A-2020,W80 Tyler TX,Hard,32,80,20201026,102,211552,NaN,Harmony Tan,R,NaN,FRA,23.123888,223451,WC,Chloe Henderson,U,NaN,USA,NaN,6-0 6-2,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238.0,270.0,NaN,NaN,3158,613701.83
185999,2020-W-ITF-USA-47A-2020,W100 Charleston SC,Clay,32,100,20201102,106,211552,NaN,Harmony Tan,R,NaN,FRA,23.143053,223452,WC,Emma Charney,U,NaN,USA,NaN,6-1 6-1,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.0,270.0,NaN,NaN,3466,562172.86
186009,2020-W-ITF-USA-47A-2020,W100 Charleston SC,Clay,32,100,20201102,116,211342,NaN,Gabriela Talaba,L,NaN,ROU,25.196441,223318,WC,Whitley Pate,U,NaN,USA,NaN,6-0 6-0,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217.0,298.0,NaN,NaN,3466,562172.86
186064,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,116,223453,WC,Brooklyn Olson,U,NaN,USA,NaN,206277,NaN,Marine Partaud,R,NaN,FRA,26.001369,1-6 6-4 10-7,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,501.0,82.0,2312,471620.95
186072,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,208,215306,NaN,Emiliana Arango,R,NaN,COL,19.947981,223453,WC,Brooklyn Olson,U,NaN,USA,NaN,6-1 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,493.0,83.0,NaN,NaN,2312,471620.95

In [8]:
tennis.drop_duplicates()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
0,2019-M020,Brisbane,Hard,32,A,20181231,300,105453,NaN,Kei Nishikori,R,178.0,JPN,29.004791,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,6-4 3-6 6-2,3,F,124.0,3.0,3.0,77.0,44.0,31.0,17.0,13.0,3.0,6.0,8.0,6.0,100.0,54.0,34.0,20.0,14.0,10.0,15.0,9.0,3590.0,16.0,1977.0,3928,742618.69
1,2019-M020,Brisbane,Hard,32,A,20181231,299,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,104542,PR,Jo-Wilfried Tsonga,R,188.0,FRA,33.705681,7-6(6) 6-2,3,SF,82.0,10.0,1.0,52.0,33.0,28.0,14.0,10.0,0.0,1.0,17.0,2.0,77.0,52.0,36.0,7.0,10.0,10.0,13.0,16.0,1977.0,239.0,200.0,3928,742618.69
2,2019-M020,Brisbane,Hard,32,A,20181231,298,105453,NaN,Kei Nishikori,R,178.0,JPN,29.004791,104871,NaN,Jeremy Chardy,R,188.0,FRA,31.882272,6-2 6-2,3,SF,66.0,2.0,2.0,47.0,33.0,26.0,9.0,8.0,2.0,2.0,10.0,3.0,46.0,27.0,15.0,6.0,8.0,1.0,5.0,9.0,3590.0,40.0,1050.0,3928,742618.69
3,2019-M020,Brisbane,Hard,32,A,20181231,297,104542,PR,Jo-Wilfried Tsonga,R,188.0,FRA,33.705681,200282,NaN,Alex De Minaur,R,183.0,AUS,19.868583,6-4 7-6(2),3,QF,106.0,12.0,2.0,68.0,43.0,34.0,15.0,11.0,4.0,5.0,1.0,2.0,81.0,60.0,38.0,9.0,11.0,4.0,6.0,239.0,200.0,31.0,1298.0,3928,742618.69
4,2019-M020,Brisbane,Hard,32,A,20181231,296,106421,NaN,Daniil Medvedev,R,198.0,RUS,22.885695,105683,NaN,Milos Raonic,R,196.0,CAN,28.010951,6-7(2) 6-3 6-4,3,QF,129.0,12.0,3.0,105.0,68.0,48.0,25.0,16.0,8.0,8.0,29.0,5.0,94.0,56.0,46.0,19.0,15.0,2.0,4.0,16.0,1977.0,18.0,1855.0,3928,742618.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186068,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,204,215794,WC,Hurricane Tyra Black,R,NaN,USA,19.690623,222081,NaN,Eleana Yu,R,NaN,USA,16.002738,7-6(1) 6-1,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,598.0,57.0,1216.0,6.0,2312,471620.95
186069,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,205,210754,NaN,Vivian Heisen,U,NaN,GER,26.869268,220723,NaN,Jessica Livianu,R,NaN,USA,22.713210,2-6 6-2 10-3,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,429.0,102.0,729.0,35.0,2312,471620.95
186070,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,206,211874,NaN,Victoria Rodriguez,U,NaN,MEX,25.552361,202478,NaN,Tara Moore,R,NaN,GBR,28.260096,6-2 7-6(8),3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,643.0,48.0,454.0,93.0,2312,471620.95
186071,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,207,213789,NaN,Katarina Jokic,U,NaN,BIH,22.559890,205922,NaN,Chanelle Van Nguyen,U,NaN,USA,26.806297,6-4 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,923.0,17.0,627.0,51.0,2312,471620.95
186072,2020-W-ITF-USA-48A-2020,W25 Orlando FL,Hard,32,25,20201109,208,215306,NaN,Emiliana Arango,R,NaN,COL,19.947981,223453,WC,Brooklyn Olson,U,NaN,USA,NaN,6-1 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,493.0,83.0,NaN,NaN,2312,471620.95

In [8]:
def f(x):
    if not x.is_integer() and x != np.nan:
        return x
    
tennis.minutes.apply(lambda x: f(x))

True

In [4]:
tennis.isna().sum()

tourney_id                 0
tourney_name               0
surface                  162
draw_size                  0
tourney_level              0
tourney_date               0
match_num                  0
winner_id                  0
winner_entry          160251
winner_name                0
winner_hand               16
winner_ht             136745
winner_ioc                 0
winner_age              2828
loser_id                   0
loser_entry           141927
loser_name                 0
loser_hand                71
loser_ht              147729
loser_ioc                  0
loser_age               6502
score                    175
best_of                    0
round                      0
minutes               104437
w_ace                 103789
w_df                  103789
w_svpt                103789
w_1stIn               103789
w_1stWon              103789
w_2ndWon              103789
w_SvGms               103785
w_bpSaved             103789
w_bpFaced             103789
l_ace                 103789
l_df                  103789
l_svpt                103789
l_1stIn               103789
l_1stWon              103789
l_2ndWon              103789
l_SvGms               103785
l_bpSaved             103789
l_bpFaced             103789
winner_rank            19379
winner_rank_points     19395
loser_rank             35256
loser_rank_points      35272
tourney_spectators         0
tourney_revenue            0
dtype: int64

In [5]:
tennis[tennis.winner_id == 210754].head(50)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
12835,2017-W-WITF-AUS-10A-2017,Brisbane $25K,Hard,32,25,20170925,3,210754,NaN,Vivian Heisen,U,NaN,GER,23.745380,215489,NaN,Ramu Ueda,U,NaN,JPN,19.523614,6-1 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,333.0,131.0,701.0,27.0,2873,531279.53
17973,2017-W-WITF-GBR-09A-2017,Manchester $100K,Grass,32,100,20170612,10,210754,Q,Vivian Heisen,U,NaN,GER,23.457906,215431,WC,Emily Appleton,U,NaN,GBR,17.779603,3-6 7-6(4) 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,543.0,49.0,884.0,14.0,3388,805983.70
18300,2017-W-WITF-GER-02A-2017,Altenkirchen $25K,Carpet,32,25,20170213,12,210754,Q,Vivian Heisen,U,NaN,GER,23.132101,201670,NaN,Amra Sadikovic,R,NaN,SUI,27.775496,6-2 0-6 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0,57.0,167.0,340.0,2665,519081.74
18310,2017-W-WITF-GER-02A-2017,Altenkirchen $25K,Carpet,32,25,20170213,22,210754,Q,Vivian Heisen,U,NaN,GER,23.132101,214081,WC,Katharina Hobgarski,R,NaN,GER,19.657769,7-5 4-6 6-2,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0,57.0,339.0,119.0,2665,519081.74
18635,2017-W-WITF-GER-13A-2017,Leipzig $25K,Clay,32,25,20170814,6,210754,NaN,Vivian Heisen,U,NaN,GER,23.630390,213694,Q,Lisa Matviyenko,R,NaN,GER,19.854894,4-6 6-2 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343.0,123.0,462.0,68.0,3076,519375.27
18666,2017-W-WITF-GER-14A-2017,Braunschweig $25K,Clay,32,25,20170821,6,210754,NaN,Vivian Heisen,U,NaN,GER,23.649555,206251,NaN,Kimberley Zimmermann,R,NaN,BEL,21.782341,6-3 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349.0,117.0,353.0,115.0,2446,585331.39
21362,2017-W-WITF-KAZ-05A-2017,Astana $100K,Hard,32,100,20170717,8,210754,NaN,Vivian Heisen,U,NaN,GER,23.553730,201485,NaN,Alla Kudryavtseva,R,NaN,RUS,29.702943,1-6 7-5 7-6(5),3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,458.0,67.0,211.0,254.0,1936,359821.81
21374,2017-W-WITF-KAZ-05A-2017,Astana $100K,Hard,32,100,20170717,20,210754,NaN,Vivian Heisen,U,NaN,GER,23.553730,206162,NaN,Kamila Kerimbayeva,R,NaN,KAZ,22.080767,6-2 4-6 6-1,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,458.0,67.0,364.0,106.0,1936,359821.81
21380,2017-W-WITF-KAZ-05A-2017,Astana $100K,Hard,32,100,20170717,26,210754,NaN,Vivian Heisen,U,NaN,GER,23.553730,210337,LL,Natalija Kostic,R,NaN,SRB,22.978782,6-4 6-3,3,QF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,458.0,67.0,560.0,44.0,1936,359821.81
24126,2017-W-WITF-SWE-02A-2017,Ystad $25K,Clay,32,25,20170619,15,210754,NaN,Vivian Heisen,U,NaN,GER,23.477070,201699,NaN,Martina Caregaro,R,NaN,ITA,25.084189,3-6 6-3 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,462.0,68.0,391.0,96.0,3207,495258.78
24135,2017-W-WITF-SWE-02A-2017,Ystad $25K,Clay,32,25,20170619,24,210754,NaN,Vivian Heisen,U,NaN,GER,23.477070,206037,NaN,Daniela Seguel,U,NaN,CHI,24.591376,6-4 5-7 6-3,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,462.0,68.0,189.0,299.0,3207,495258.78
24145,2017-W-WITF-SWE-03A-2017,Lund $25K,Clay,32,25,20170626,3,210754,Q,Vivian Heisen,U,NaN,GER,23.496235,206250,Q,Michaela Boev,U,NaN,BEL,25.979466,6-4 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,475.0,67.0,854.0,16.0,3115,542900.20
36625,2016-W-C10-BRN-01A-2016,Manama $10K,Hard,32,10,20160328,9,210754,NaN,Vivian Heisen,U,NaN,GER,22.250513,204415,NaN,Alexandra Riley,U,NaN,USA,24.958248,6-3 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,37.0,845.0,16.0,2201,447934.21
36637,2016-W-C10-BRN-01A-2016,Manama $10K,Hard,32,10,20160328,21,210754,NaN,Vivian Heisen,U,NaN,GER,22.250513,215827,Q,Tanasha Khandpur,R,NaN,IND,19.392197,6-1 6-0,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,37.0,NaN,NaN,2201,447934.21
42827,2016-W-C10-NED-02A-2016,Breda $10K,Clay,32,10,20160620,4,210754,NaN,Vivian Heisen,U,NaN,GER,22.480493,210108,Q,Sandy Marti,R,NaN,SUI,23.991786,6-1 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,43.0,NaN,NaN,2113,498162.70
42841,2016-W-C10-NED-02A-2016,Breda $10K,Clay,32,10,20160620,18,210754,NaN,Vivian Heisen,U,NaN,GER,22.480493,211775,Q,Erika Vogelsang,R,NaN,NED,21.305955,6-0 6-3,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,43.0,854.0,14.0,2113,498162.70
42848,2016-W-C10-NED-02A-2016,Breda $10K,Clay,32,10,20160620,25,210754,NaN,Vivian Heisen,U,NaN,GER,22.480493,204394,NaN,Valentini Grammatikopoulou,U,NaN,GRE,19.359343,6-7(1) 7-6(3) 7-6(2),3,QF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,43.0,332.0,115.0,2113,498162.70
42852,2016-W-C10-NED-02A-2016,Breda $10K,Clay,32,10,20160620,29,210754,NaN,Vivian Heisen,U,NaN,GER,22.480493,206292,NaN,Astra Sharma,R,NaN,AUS,20.774812,7-5 7-6(4),3,SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,43.0,783.0,19.0,2113,498162.70
42854,2016-W-C10-NED-02A-2016,Breda $10K,Clay,32,10,20160620,31,210754,NaN,Vivian Heisen,U,NaN,GER,22.480493,206184,NaN,Kelly Versteeg,U,NaN,NED,21.587953,6-2 6-1,3,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,561.0,43.0,536.0,48.0,2113,498162.70
47165,2016-W-C25-AUS-05A-2016,Canberra $25K,Clay,32,25,20160314,8,210754,Q,Vivian Heisen,U,NaN,GER,22.212183,201679,NaN,Varatchaya Wongteanchai,R,NaN,THA,26.516085,7-5 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,37.0,264.0,165.0,3185,669393.08
47199,2016-W-C25-AUS-06A-2016,Canberra $25K,Clay,32,25,20160321,11,210754,Q,Vivian Heisen,U,NaN,GER,22.231348,206424,Q,Katharina Lehnert,R,NaN,GER,22.086242,6-1 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,37.0,444.0,72.0,4407,1036660.61
47210,2016-W-C25-AUS-06A-2016,Canberra $25K,Clay,32,25,20160321,22,210754,Q,Vivian Heisen,U,NaN,GER,22.231348,201617,NaN,Ana Vrljic,R,NaN,CRO,31.635866,6-2 4-6 6-3,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,603.0,37.0,276.0,159.0,4407,1036660.61
48558,2016-W-C25-GER-09A-2016,Hechingen $25K,Clay,32,25,20160808,6,210754,Q,Vivian Heisen,U,NaN,GER,22.614648,202487,NaN,Nastassja Burnett,R,NaN,ITA,24.465435,6-1 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,473.0,64.0,395.0,91.0,1199,247181.71
49798,2016-W-C25-NED-01A-2016,Middelburg $25K,Clay,32,25,20160627,7,210754,NaN,Vivian Heisen,U,NaN,GER,22.499658,206175,Q,Tess Sugnaux,R,NaN,SUI,21.319644,6-3 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,560.0,44.0,548.0,47.0,3905,810803.28
118846,2018-W-WITF-AUS-10A-2018,Darwin $60K,Hard,32,60,20180924,291,210754,NaN,Vivian Heisen,U,NaN,GER,24.741958,211103,NaN,Shelby Talcott,U,NaN,USA,25.691992,6-1 6-1,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.0,37.0,704.0,30.0,2382,491352.73
118880,2018-W-WITF-AUS-11A-2018,Brisbane $25K,Hard,32,25,20181001,16,210754,NaN,Vivian Heisen,U,NaN,GER,24.761123,213602,NaN,Gabriella Taylor,R,NaN,GBR,20.569473,6-2 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.0,37.0,175.0,336.0,3630,764228.12
118888,2018-W-WITF-AUS-11A-2018,Brisbane $25K,Hard,32,25,20181001,24,210754,NaN,Vivian Heisen,U,NaN,GER,24.761123,214540,Q,Chihiro Muramatsu,U,NaN,JPN,20.361396,6-3 4-6 7-5,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.0,37.0,373.0,108.0,3630,764228.12
118892,2018-W-WITF-AUS-11A-2018,Brisbane $25K,Hard,32,25,20181001,28,210754,NaN,Vivian Heisen,U,NaN,GER,24.761123,213646,NaN,Dalma Galfi,U,NaN,HUN,20.134155,6-3 7-5,3,QF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.0,37.0,287.0,174.0,3630,764228.12
119239,2018-W-WITF-BLR-03A-2018,Minsk $25K,Hard,32,25,20181105,3,210754,Q,Vivian Heisen,U,NaN,GER,24.856947,215554,NaN,Maryna Chernyshova,U,NaN,UKR,19.364819,6-2 1-6 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,558.0,51.0,403.0,94.0,4217,730845.97
124337,2018-W-WITF-GER-14A-2018,Braunschweig $25K,Clay,32,25,20180820,10,210754,NaN,Vivian Heisen,U,NaN,GER,24.646133,214081,NaN,Katharina Hobgarski,R,NaN,GER,21.171800,6-1 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605.0,42.0,326.0,144.0,2623,488917.33
124348,2018-W-WITF-GER-14A-2018,Braunschweig $25K,Clay,32,25,20180820,21,210754,NaN,Vivian Heisen,U,NaN,GER,24.646133,202688,NaN,Isabella Shinikova,R,NaN,BUL,26.819986,6-3 7-5,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605.0,42.0,276.0,183.0,2623,488917.33
126167,2018-W-WITF-ITA-21A-2018,Torino $25K,Clay,32,25,20180709,11,210754,NaN,Vivian Heisen,U,NaN,GER,24.531143,214254,Q,Alice Rame,U,NaN,FRA,20.662560,6-2 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.0,101.0,518.0,62.0,4161,933082.28
128578,2018-W-WITF-POR-02A-2018,Obidos $25K,Carpet,32,25,20180416,10,210754,NaN,Vivian Heisen,U,NaN,GER,24.301164,216293,NaN,Rita Maria Bentes De Oliveira Pinto,R,NaN,POR,17.678303,6-2 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346.0,121.0,NaN,NaN,3900,1019241.47
130041,2018-W-WITF-SVK-01A-2018,Trnava $15K,Hard,32,15,20180205,16,210754,NaN,Vivian Heisen,U,NaN,GER,24.109514,220292,NaN,Kiara Petrovicka,U,NaN,SVK,17.856263,6-3 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.0,131.0,NaN,NaN,3434,590396.36
130049,2018-W-WITF-SVK-01A-2018,Trnava $15K,Hard,32,15,20180205,24,210754,NaN,Vivian Heisen,U,NaN,GER,24.109514,221007,NaN,Nina Stankovska,U,NaN,SVK,16.013689,6-1 6-4,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,338.0,131.0,NaN,NaN,3434,590396.36
143029,2019-W-ITF-FRA-22A-2019,W60 Nantes,Hard,32,60,20191028,6,210754,NaN,Vivian Heisen,U,NaN,GER,25.834360,214238,Q,Verena Meliss,U,NaN,ITA,22.269678,6-4 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,463.0,86.0,511.0,72.0,2876,610017.61
143402,2019-W-ITF-GBR-01B-2019,W25 Roehampton,Hard,32,25,20190916,14,210754,NaN,Vivian Heisen,U,NaN,GER,25.719370,205922,Q,Chanelle Van Nguyen,U,NaN,USA,25.656400,6-2 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,88.0,685.0,35.0,1658,322186.99
143419,2019-W-ITF-GBR-01B-2019,W25 Roehampton,Hard,32,25,20190916,23,210754,NaN,Vivian Heisen,U,NaN,GER,25.719370,202707,NaN,Myrtille Georges,R,NaN,FRA,28.736482,6-1 6-1,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,88.0,238.0,250.0,1658,322186.99
143426,2019-W-ITF-GBR-01B-2019,W25 Roehampton,Hard,32,25,20190916,28,210754,NaN,Vivian Heisen,U,NaN,GER,25.719370,221054,NaN,Emma Raducanu,R,NaN,GBR,16.840520,7-5 4-1 RET,3,QF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,88.0,548.0,59.0,1658,322186.99
143696,2019-W-ITF-GBR-06A-2019,W100 Manchester,Grass,32,100,20190610,2,210754,NaN,Vivian Heisen,U,NaN,GER,25.451061,215912,NaN,Katarzyna Pitak,U,NaN,GBR,20.706366,6-1 6-2,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,455.0,67.0,NaN,NaN,3082,616692.18
143717,2019-W-ITF-GBR-06A-2019,W100 Manchester,Grass,32,100,20190610,13,210754,NaN,Vivian Heisen,U,NaN,GER,25.451061,215043,NaN,Qianhui Tang,R,NaN,CHN,18.746064,6-0 6-2,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,455.0,67.0,647.0,20.0,3082,616692.18
143807,2019-W-ITF-GBR-08A-2019,W25 Woking,Hard,32,25,20190729,9,210754,NaN,Vivian Heisen,U,NaN,GER,25.585216,202425,NaN,Samantha Murray,R,NaN,GBR,31.802875,6-2 7-6(6),3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.0,86.0,328.0,137.0,2627,599616.51
143831,2019-W-ITF-GBR-08A-2019,W25 Woking,Hard,32,25,20190729,21,210754,NaN,Vivian Heisen,U,NaN,GER,25.585216,210926,Q,Pei Chi Lee,U,NaN,TPE,24.783025,7-6(5) 6-4,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,414.0,86.0,725.0,13.0,2627,599616.51
144145,2019-W-ITF-GER-02A-2019,W25 Altenkirchen,Carpet,32,25,20190218,7,210754,NaN,Vivian Heisen,U,NaN,GER,25.144422,210672,NaN,Polina Leykina,R,NaN,RUS,24.413415,6-2 6-2,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,462.0,55.0,338.0,120.0,3005,663495.03
144462,2019-W-ITF-GER-08A-2019,W25 Darmstadt,Clay,32,25,20190624,7,210754,NaN,Vivian Heisen,U,NaN,GER,25.489391,215515,NaN,Katerina Filip,R,NaN,SWE,19.811088,6-2 6-4,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,440.0,72.0,NaN,NaN,4520,767593.36
144731,2019-W-ITF-GER-13A-2019,W25 Leipzig,Clay,32,25,20190812,7,210754,NaN,Vivian Heisen,U,NaN,GER,25.623546,210742,NaN,Mariana Drazic,R,NaN,CRO,24.591376,6-1 6-0,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,416.0,97.0,873.0,16.0,3033,622101.56
144757,2019-W-ITF-GER-13A-2019,W25 Leipzig,Clay,32,25,20190812,20,210754,NaN,Vivian Heisen,U,NaN,GER,25.623546,211285,NaN,Tayisiya Morderger,L,NaN,GER,22.431211,6-2 6-0,3,Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,416.0,97.0,571.0,53.0,3033,622101.56
147032,2019-W-ITF-ITA-07A-2019,W25 Rome,Clay,32,25,20190506,11,210754,NaN,Vivian Heisen,U,NaN,GER,25.355236,214322,NaN,Karolayne Alexandre Da Rosa,U,NaN,BRA,21.508556,7-5 7-5,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.0,67.0,865.0,3.0,3265,561516.07
149355,2019-W-ITF-KAZ-05A-2019,W80 Nur Sultan,Hard,32,80,20190715,7,210754,NaN,Vivian Heisen,U,NaN,GER,25.546886,203555,NaN,Mai Minokoshi,U,NaN,JPN,27.244353,6-4 6-3,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,72.0,404.0,92.0,3456,853751.34
149378,2019-W-ITF-KAZ-05A-2019,W80 Nur Sultan,Hard,32,80,20190715,20,210754,NaN,Vivian Heisen,U,NaN,GER,25.546886,213793,NaN,Gozal Ainitdinova,U,NaN,KAZ,20.895277,6-2 3-6 7-5,3,R16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,72.0,522.0,44.0,3456,853751.34

In [ ]:
tennis.info()

In [ ]:
tennis.surface.value_counts()

In [ ]:
tennis.winner_ht

In [ ]:
set(tennis.surface)

In [ ]:
set(tennis.loser_entry)

In [21]:
tennis.tourney_id + tennis.tourney_name

0                             2019-M020Brisbane
1                             2019-M020Brisbane
2                             2019-M020Brisbane
3                             2019-M020Brisbane
4                             2019-M020Brisbane
                          ...
186068    2020-W-ITF-USA-48A-2020W25 Orlando FL
186069    2020-W-ITF-USA-48A-2020W25 Orlando FL
186070    2020-W-ITF-USA-48A-2020W25 Orlando FL
186071    2020-W-ITF-USA-48A-2020W25 Orlando FL
186072    2020-W-ITF-USA-48A-2020W25 Orlando FL
Length: 186073, dtype: object

In [28]:
tennis[['tourney_id', 'tourney_name', 'tourney_date', 'surface', 'draw_size', 'tourney_level', 'tourney_spectators', 'tourney_revenue']].drop_duplicates()

,tourney_id,tourney_name,tourney_date,surface,draw_size,tourney_level,tourney_spectators,tourney_revenue
0,2019-M020,Brisbane,20181231,Hard,32,A,3928,742618.69
27,2019-M020,Brisbane,20181231,Hard,32,P,3928,742618.69
96,2019-0451,Doha,20181231,Hard,32,A,2923,550943.19
139,2019-0891,Pune,20181231,Hard,32,A,4062,1005592.39
178,2019-0301,Auckland,20190107,Hard,32,A,2784,489426.09
...,...,...,...,...,...,...,...,...
185798,2020-W-ITF-USA-08A-2020,W25 Las Vegas NV,20200302,Hard,32,25,2467,430385.13
185853,2020-W-ITF-USA-40A-2020,W80 Macon GA,20201019,Hard,32,80,3458,778494.53
185908,2020-W-ITF-USA-42A-2020,W80 Tyler TX,20201026,Hard,32,80,3158,613701.83
185963,2020-W-ITF-USA-47A-2020,W100 Charleston SC,20201102,Clay,32,100,3466,562172.86
186018,2020-W-ITF-USA-48A-2020,W25 Orlando FL,20201109,Hard,32,25,2312,471620.95

In [12]:
tennis[['tourney_id', 'match_num', 'tourney_date', 'winner_name', 'loser_name']].drop_duplicates()

,tourney_id,match_num,tourney_date,winner_name,loser_name
0,2019-M020,300,20181231,Kei Nishikori,Daniil Medvedev
1,2019-M020,299,20181231,Daniil Medvedev,Jo-Wilfried Tsonga
2,2019-M020,298,20181231,Kei Nishikori,Jeremy Chardy
3,2019-M020,297,20181231,Jo-Wilfried Tsonga,Alex De Minaur
4,2019-M020,296,20181231,Daniil Medvedev,Milos Raonic
...,...,...,...,...,...
186068,2020-W-ITF-USA-48A-2020,204,20201109,Hurricane Tyra Black,Eleana Yu
186069,2020-W-ITF-USA-48A-2020,205,20201109,Vivian Heisen,Jessica Livianu
186070,2020-W-ITF-USA-48A-2020,206,20201109,Victoria Rodriguez,Tara Moore
186071,2020-W-ITF-USA-48A-2020,207,20201109,Katarina Jokic,Chanelle Van Nguyen
186072,2020-W-ITF-USA-48A-2020,208,20201109,Emiliana Arango,Brooklyn Olson

In [26]:
tennis[['tourney_id', 'tourney_date', 'tourney_level']].drop_duplicates()

                     tourney_id  tourney_date tourney_level
0                     2019-M020      20181231             A
27                    2019-M020      20181231             P
96                    2019-0451      20181231             A
139                   2019-0891      20181231             A
178                   2019-0301      20190107             A
...                         ...           ...           ...
185798  2020-W-ITF-USA-08A-2020      20200302            25
185853  2020-W-ITF-USA-40A-2020      20201019            80
185908  2020-W-ITF-USA-42A-2020      20201026            80
185963  2020-W-ITF-USA-47A-2020      20201102           100
186018  2020-W-ITF-USA-48A-2020      20201109            25

[4911 rows x 3 columns]

In [20]:
tennis[['tourney_id', 'tourney_name', 'tourney_date', 'surface', 'draw_size', 'tourney_level', 'tourney_spectators', 'tourney_revenue']]

8

In [9]:
tennis[tennis.winner_id == 144773]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,tourney_spectators,tourney_revenue
76305,2017-0252,Medellin CH,Clay,32,C,20170710,244,144773,NaN,Jose Olivares,NaN,NaN,DOM,20.501027,126666,WC,Felipe Ramirez Luna,U,NaN,COL,19.485284,6-2 6-4,3,Q2,67.0,7.0,1.0,48.0,28.0,25.0,9.0,9.0,1.0,2.0,0.0,4.0,55.0,27.0,18.0,13.0,9.0,5.0,9.0,731.0,29.0,NaN,NaN,3374,690043.74
76312,2017-0252,Medellin CH,Clay,32,C,20170710,251,144773,NaN,Jose Olivares,NaN,NaN,DOM,20.501027,106059,NaN,Michel Vernier,R,NaN,CHI,24.783025,6-7(3) 6-1 6-4,3,Q3,120.0,3.0,4.0,96.0,62.0,48.0,18.0,15.0,3.0,4.0,0.0,3.0,81.0,53.0,37.0,16.0,14.0,5.0,9.0,731.0,29.0,970.0,12.0,3374,690043.74
80440,2017-5016,Floridablanca CH,Clay,32,C,20170807,239,144773,NaN,Jose Olivares,NaN,NaN,DOM,20.577687,125808,NaN,Jose Antonio Rodriguez Rodriguez,U,NaN,MEX,22.288843,3-6 6-0 6-3,3,Q1,87.0,9.0,1.0,70.0,40.0,32.0,14.0,12.0,1.0,3.0,1.0,11.0,78.0,45.0,28.0,13.0,12.0,3.0,8.0,700.0,33.0,1484.0,2.0,3794,790352.10
80450,2017-5016,Floridablanca CH,Clay,32,C,20170807,249,144773,NaN,Jose Olivares,NaN,NaN,DOM,20.577687,122538,NaN,Nicolas Alberto Arreche,U,NaN,ARG,22.893908,6-3 6-2,3,Q2,77.0,0.0,3.0,65.0,38.0,26.0,14.0,8.0,4.0,5.0,3.0,5.0,57.0,31.0,19.0,10.0,9.0,7.0,12.0,700.0,33.0,1562.0,2.0,3794,790352.10
111617,2018-6284,Guadalajara CH,Hard,32,C,20180416,237,144773,WC,Jose Olivares,NaN,NaN,DOM,21.267625,133715,WC,Mauricio Rivera Caballero,R,NaN,MEX,20.933607,6-3 6-3,3,Q1,69.0,9.0,4.0,51.0,32.0,31.0,7.0,9.0,1.0,1.0,0.0,4.0,62.0,45.0,30.0,5.0,9.0,3.0,6.0,910.0,14.0,NaN,NaN,3072,578917.46
115781,2018-7911,Puerto Vallarta CH,Hard,32,C,20180430,232,144773,NaN,Jose Olivares,NaN,NaN,DOM,21.305955,105434,NaN,Ruan Roelofse,R,NaN,RSA,28.446270,6-3 7-5,3,Q1,NaN,4.0,2.0,67.0,39.0,32.0,12.0,11.0,1.0,2.0,1.0,5.0,66.0,43.0,28.0,11.0,10.0,6.0,9.0,907.0,14.0,683.0,32.0,2235,397363.34

In [10]:
tennis.w_ace

0          3.0
1         10.0
2          2.0
3         12.0
4         12.0
          ...
186068     NaN
186069     NaN
186070     NaN
186071     NaN
186072     NaN
Name: w_ace, Length: 186073, dtype: float64

In [16]:
set(tennis.tourney_level)

{'10',
 '100',
 100,
 15,
 '15',
 25,
 '25',
 '50',
 60,
 '60',
 '75',
 80,
 '80',
 'A',
 'C',
 'D',
 'F',
 'G',
 'I',
 'M',
 'O',
 'P',
 'PM',
 'W'}

In [12]:
female

           name     surname
0         Bobby       Riggs
1             X           X
2       Martina      Hingis
3       Mirjana       Lucic
4       Justine       Henin
...         ...         ...
46167  Kathleen       Allen
46168       Mrs  Dransfield
46169    Jessie      Greene
46170      Mary    Trumbull
46171      Inga    Sperling

[46172 rows x 2 columns]

In [13]:
tennis[tennis.winner_name == 'X X']

Empty DataFrame
Columns: [tourney_id, tourney_name, surface, draw_size, tourney_level, tourney_date, match_num, winner_id, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, winner_age, loser_id, loser_entry, loser_name, loser_hand, loser_ht, loser_ioc, loser_age, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced, winner_rank, winner_rank_points, loser_rank, loser_rank_points, tourney_spectators, tourney_revenue]
Index: []

In [14]:
tennis[tennis.surface.isna()][['tourney_name', 'surface']]

                       tourney_name surface
86167     Fed Cup G2 RR: ECU vs CUB     NaN
86168     Fed Cup G2 RR: ECU vs CUB     NaN
86169     Fed Cup G2 RR: ECU vs URU     NaN
86170     Fed Cup G2 RR: ECU vs URU     NaN
86171     Fed Cup G2 RR: URU vs CUB     NaN
...                             ...     ...
162962  Davis Cup G2 R1: VIE vs HKG     NaN
162995  Davis Cup G1 R1: TPE vs CHN     NaN
162996  Davis Cup G1 R1: TPE vs CHN     NaN
162997  Davis Cup G1 R1: TPE vs CHN     NaN
162998  Davis Cup G1 R1: TPE vs CHN     NaN

[162 rows x 2 columns]

In [42]:
tennis.tourney_date.value_counts()

20190826    1440
20190715    1224
20190916    1191
20190909    1185
20191021    1182
            ...
20180620       4
20170217       4
20181123       3
20181110       3
20191124       2
Name: tourney_date, Length: 375, dtype: int64